version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: scrum_master_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scrum_master_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - scrum-network

  # Backend API (Node.js)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: scrum_master_dev
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 3000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - scrum-network
    restart: unless-stopped

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - scrum-network
    restart: unless-stopped

volumes:
  postgres_data_dev:

networks:
  scrum-network:
    driver: bridge